# Put the commented values in your .crowdin.yml file
# project_id: "CROWDIN_PROJECT_ID"
# api_token: "CROWDIN_PERSONAL_TOKEN"
base_path: "."
base_url: "https://microbolt.api.crowdin.com"

preserve_hierarchy: true

files: [
  {
    source: "/locales/en.js",
    translation: "/locales/%two_letters_code%.js",
    type: "js"
  },
  {
    source: "/pages/en/**/*.mdx",
    translation: "/pages/%two_letters_code%/**/%original_file_name%",
    type: "mdx_v2",
    ignore: [
      "/pages/en/docs/ashigaru/*.mdx",
      "/pages/en/docs/darkirc/*.mdx",
      "/pages/en/docs/liquid/*.mdx"
    ]
  },
  {
    source: "/pages/en/**/*.md",
    translation: "/pages/%two_letters_code%/**/%original_file_name%",
    type: "mdx_v2",
    ignore: [
      "/pages/en/docs/ashigaru.md",
      "/pages/en/docs/darkirc.md",
      "/pages/en/docs/liquid.md"
    ]
  },
  {
    source: "/pages/en/**/*.js",
    translation: "/pages/%two_letters_code%/**/%original_file_name%",
    type: "js",
    ignore: [
      "/pages/en/docs/ashigaru/_meta.js",
      "/pages/en/docs/darkirc/_meta.js",
      "/pages/en/docs/liquid/_meta.js"
    ]
  }
]