# Put the commented values in your .crowdin.yml file
project_id: "1"
# api_token: "CROWDIN_PERSONAL_TOKEN"
base_path: "."
base_url: "https://microbolt.api.crowdin.com"

preserve_hierarchy: true

files: [
  {
    source: "/locales/en.js",
    translation: "/locales/%two_letters_code%.js",
    type: "js"
  },
  {
    source: "/pages/en/**/*.html",
    translation: "/pages/%two_letters_code%/**/%original_file_name%",
    type: "html"
  },
  {
    source: "/pages/en/**/*.js",
    translation: "/pages/%two_letters_code%/**/%original_file_name%",
    type: "js",
    ignore: [
      "/pages/en/**/darkirc",
      "/pages/en/**/liquid"
    ]
  },
  {
    source: "/pages/en/**/*.mdx",
    translation: "/pages/%two_letters_code%/**/%original_file_name%",
    type: "mdx_v2",
    ignore: [
      "/pages/en/**/darkirc",
      "/pages/en/**/liquid",
      "/pages/en/**/darkirc.mdx",
      "/pages/en/**/liquid.mdx"
    ]
  }
]